### ISSUE TITLE
Let's migrate to Modern?

### ISSUE THREAD

**Issue by jgcmarins** [nodkz/northwind-relay-example-app#4]
Hello, @nodkz 

Are you accepting PRs migrating to Relay Modern?
I'd love to help!

If it's ok, just let me know how can I contribute 😄

**Comment by nodkz** [comment]
It will be cool! 👍
For now, I'm stuck with our internal app (it also on relay classic) and have no time to do it myself. BUT if you interested to help, let's do it!

> If it's ok, just let me know how can I contribute 😄
- fork repo
- create branch `modern` in your forked repo
- make some changes and make commit (it may just upgrade packages for the start)
- open your forked repo on github and make PR to my repo (there should be a checkbox which allows to me send commits to your repo. In such case I will have access to make commits directly to your forked repo, they will be automatically translated to PR in this repo, and you will no need makes merges from *upstream* while we work together inside your fork. In other words, all work on migration to Relay Modern will be in your forked repo.  When all work will be done, I just merge it with master.)
- All discussion and TODO we can keep in your upcoming PR. 😉

Thanks for help!

**Comment by jgcmarins** [comment]
Great! \o/
Thanks, @nodkz

**Comment by nodkz** [comment]
I'm started own [modern](https://github.com/nodkz/relay-northwind-app/tree/modern) branch. I saw too much outdated packages, so updated them myself.

Tomorrow I'll try to make app alive with new packages on new relay package in classic mode. Only after that, we can go further.

**Comment by jgcmarins** [comment]
Nice!

**Comment by nodkz** [comment]
Relay Modern in master branch now.

**Comment by jgcmarins** [comment]
Wow, great job!
